
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@mui/material/styles'; //Contexto
import { GoogleOAuthProvider } from '@react-oauth/google';
import theme from "../app/Theme.js";
import { useTheme } from '@mui/material/styles'; //esta va ligada al provider
import GeneralProviders from "./components/GeneralProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       
      <body style={{ margin: 0 }} className={inter.className}>
      <GeneralProviders children={children}></GeneralProviders>
   {/*    <GoogleOAuthProvider clientId="862893519032-2oupdld0qpkck0fk4rp29otd6gf3v7jq.apps.googleusercontent.com">
        <ThemeProvider theme={ theme }>
          {children}
        </ThemeProvider>
      </GoogleOAuthProvider> */}
   
     
      </body>
    </html>
  );
}
